# Dockerfile generated by DevOpsArk

# Use official Node.js LTS image as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY package.json package-lock.json ./

# Install npm dependencies
RUN npm ci --only=production

# Copy application source code
COPY . .

# Expose the application port (change if your app uses a different port)
EXPOSE 3000

# Start the Node.js application
CMD ["node", "index.js"]